<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use App\Models\Recipe;
use App\Models\Ingredients;
use App\Models\Unit;
use App\Models\Country;

class ContohResepSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('recipe')->truncate();

        DB::transaction(function () {

            $recipes = [
                [
                    'name' => 'Sate Ayam Madura',
                    'image' => 'sate-ayam.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 45,
                    'ingredients' => [
                        ['name' => 'Daging Ayam Fillet', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Potong dadu'],
                        ['name' => 'Kacang Tanah', 'amount' => 150, 'unit' => 'gr', 'notes' => 'Goreng dan haluskan'],
                        ['name' => 'Kecap Manis', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Bawang Merah', 'amount' => 8, 'unit' => 'siung', 'notes' => 'Untuk bumbu dan taburan'],
                    ],
                    'steps' => [
                        'Potong daging ayam bentuk dadu, tusuk dengan tusukan sate.',
                        'Haluskan bumbu: kacang tanah, bawang merah, bawang putih, kemiri, dan cabai.',
                        'Tumis bumbu halus hingga harum, tambahkan kecap manis, air, dan garam. Masak hingga mengental.',
                        'Lumuri sate dengan sebagian bumbu, diamkan 15 menit.',
                        'Bakar sate di atas bara api hingga matang sambil diolesi sisa bumbu.',
                        'Sajikan sate dengan sisa bumbu kacang, irisan bawang merah, dan lontong.',
                    ],
                ],
                [
                    'name' => 'Nasi Goreng Spesial',
                    'image' => 'nasi-goreng.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 30,
                    'ingredients' => [
                        ['name' => 'Nasi Putih', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Dingin lebih baik'],
                        ['name' => 'Telur Ayam', 'amount' => 2, 'unit' => 'butir', 'notes' => 'Kocok lepas'],
                        ['name' => 'Kecap Manis', 'amount' => 2, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Cincang halus'],
                    ],
                    'steps' => [
                        'Panaskan minyak, tumis bawang putih hingga harum.',
                        'Masukkan telur, orak-arik hingga matang.',
                        'Masukkan nasi, kecap manis, garam, dan lada. Aduk hingga rata.',
                        'Masak hingga nasi goreng matang dan harum, sajikan hangat.',
                    ],
                ],
                [
                    'name' => 'Udang Saus Padang',
                    'image' => 'udang-saus-padang.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 60,
                    'ingredients' => [
                        ['name' => 'Udang', 'amount' => 350, 'unit' => 'gr', 'notes' => 'Goreng sebentar 1 menit'],
                        ['name' => 'Jagung Manis', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Sudah dimasak'],
                        ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong-potong'],
                        ['name' => 'Cabe Hijau', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Iris serong'],
                        ['name' => 'Cabe Merah Besar', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Iris serong'],
                        ['name' => 'Bawang Bombay', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Iris'],
                        ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Iris'],
                        ['name' => 'Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => 'Kocok lepas'],
                        ['name' => 'Air', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Kurang lebih'],
                        ['name' => 'Larutan Maizena', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Opsional, jika ingin lebih kental'],

                        ['name' => 'Cabe Merah Keriting', 'amount' => 8, 'unit' => 'buah', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Jahe', 'amount' => 1, 'unit' => 'ruas jari', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Bawang Merah', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],

                        ['name' => 'Sasa Saus Tomat', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Sasa Saus Sambal Asli', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Saus Tiram', 'amount' => 1.5, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Kecap Inggris', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Kecap Ikan', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Gula Pasir', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Lada Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk bahan saus'],
                        ['name' => 'Sasa Bubuk MSG', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk bahan saus'],
                    ],
                    'steps' => [
                        'Blender bahan-bahan untuk bumbu halus, sisihkan.',
                        'Campurkan semua bahan saus dalam satu wadah, aduk rata.',
                        'Goreng udang selama 1 menit, angkat dan tiriskan.',
                        'Tumis bumbu halus hingga harum, kemudian masukkan campuran bahan saus.',
                        'Masukkan bawang bombay dan masak hingga sedikit layu.',
                        'Tambahkan air secukupnya dan biarkan mendidih.',
                        'Masukkan kocokan telur sambil diaduk agar berserabut.',
                        'Masukkan jagung manis dan udang, masak kembali selama 2-3 menit.',
                        'Masukkan cabe merah, cabe hijau, tomat, dan daun bawang, aduk rata kembali.',
                        'Jika dirasa kurang kental, tambahkan larutan maizena. Koreksi rasa dan sajikan.',
                    ],
                ],
                [
                    'name' => 'Ayam Kecap Mentega',
                    'image' => 'ayam-kecap-mentega.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 55,
                    'ingredients' => [
                        ['name' => 'Ayam', 'amount' => 0.5, 'unit' => 'ekor', 'notes' => 'Potong-potong kecil'],
                        ['name' => 'Bawang Putih Halus', 'amount' => 2, 'unit' => 'siung', 'notes' => 'Untuk marinasi'],
                        ['name' => 'Garam', 'amount' => 1.5, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Minyak Goreng', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Untuk menggoreng ayam'],

                        ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => 'Memarkan lalu cincang halus'],
                        ['name' => 'Bawang Bombay', 'amount' => 0.5, 'unit' => 'buah', 'notes' => 'Iris memanjang'],
                        ['name' => 'Kecap Manis', 'amount' => 3, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Kecap Inggris', 'amount' => 2, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Air', 'amount' => 50, 'unit' => 'ml', 'notes' => null],
                        ['name' => 'Gula Pasir', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Mentega', 'amount' => 3, 'unit' => 'sdm', 'notes' => null],
                    ],
                    'steps' => [
                        'Cuci bersih ayam lalu baluri seluruh permukaannya dengan bawang putih halus dan garam. Marinasi (diamkan) selama 1 jam di dalam kulkas.',
                        'Goreng ayam yang telah dimarinasi hingga matang. Angkat, tiriskan, dan sisihkan.',
                        'Panaskan 2 sdm minyak, tumis bawang putih cincang hingga harum.',
                        'Masukkan kecap manis dan kecap inggris. Aduk rata.',
                        'Tuangkan air lalu aduk rata agar tidak gosong.',
                        'Bumbui dengan garam, gula pasir, dan merica. Aduk hingga rata.',
                        'Masukkan ayam yang sudah digoreng dan irisan bawang bombay. Aduk hingga rata.',
                        'Terakhir, masukkan mentega. Masak hingga meletup-letup dan bumbu meresap. Angkat.',
                        'Siap disajikan selagi hangat.',
                    ],
                ],
                [
                    'name' => 'Tongkol Suwir',
                    'image' => 'tongkol-suwir.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 40,
                    'ingredients' => [
                        ['name' => 'Ikan Tongkol', 'amount' => 250, 'unit' => 'gr', 'notes' => 'Bisa pindang atau potongan segar'],
                        ['name' => 'Kemangi', 'amount' => 1, 'unit' => 'ikat', 'notes' => 'Petiki daunnya'],
                        ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Gula Pasir', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk memberi rasa manis'],
                        ['name' => 'Lada Bubuk', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Sasa Bumbu Ekstrak Daging Sapi', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk baluran dan bumbu'],
                        ['name' => 'Air', 'amount' => 50, 'unit' => 'ml', 'notes' => 'Sedikit saja'],
                        ['name' => 'Minyak Goreng', 'amount' => 30, 'unit' => 'ml', 'notes' => 'Untuk menggoreng dan menumis'],
                        ['name' => 'Cabai Rawit', 'amount' => 10, 'unit' => 'buah', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Cabai Merah Keriting', 'amount' => 5, 'unit' => 'buah', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Bawang Merah', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Lengkuas', 'amount' => 2, 'unit' => 'cm', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Serai', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Ambil bagian putihnya'],
                    ],
                    'steps' => [
                    'Baluri ikan tongkol dengan setengah bagian Sasa Bumbu Ekstrak Daging Sapi, lalu goreng hingga matang. Angkat dan suwir-suwir dagingnya.',
                    'Haluskan semua bahan bumbu halus (cabai, bawang, lengkuas, serai) dengan blender atau ulekan.',
                    'Panaskan sedikit minyak, tumis bumbu halus hingga harum dan matang.',
                    'Tambahkan sedikit air, lalu masukkan saus tiram, gula, lada, dan sisa Sasa Bumbu Ekstrak Daging Sapi. Aduk rata.',
                    'Masukkan ikan tongkol yang sudah disuwir, aduk hingga bumbu tercampur rata dan meresap.',
                    'Terakhir, masukkan daun kemangi, aduk sebentar hingga sedikit layu.',
                    'Koreksi rasa, angkat, dan nikmati bersama nasi putih hangat.',
                    ],
                ],
                [
                    'name' => 'Telur Dadar Krispi',
                    'image' => 'telur-dadar-krispi.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 20,
                    'ingredients' => [
                        ['name' => 'Telur Ayam', 'amount' => 2, 'unit' => 'butir', 'notes' => null],
                        ['name' => 'Garam', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Sasa Tepung Bumbu Kentucky', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Untuk adonan basah dan kering'],
                        ['name' => 'Air', 'amount' => 50, 'unit' => 'ml', 'notes' => 'Untuk adonan basah'],
                        ['name' => 'Minyak Goreng', 'amount' => 200, 'unit' => 'ml', 'notes' => 'Untuk menggoreng'],
                    ],
                    'steps' => [ 'Dalam mangkuk, campurkan telur dan garam, lalu kocok lepas.', 'Panaskan sedikit minyak di teflon, buat telur dadar tipis hingga matang. Angkat.', 'Potong telur dadar yang sudah matang menjadi 4 bagian atau sesuai selera.', 'Siapkan dua wadah: satu untuk adonan basah (campurkan Sasa Tepung Bumbu Kentucky dengan air secukupnya), satu lagi untuk tepung kering.', 'Celupkan setiap potongan telur ke dalam adonan basah hingga seluruh permukaan tertutup.', 'Balurkan potongan telur ke dalam tepung kering sambil sedikit diremas agar tepung menempel sempurna.', 'Panaskan minyak yang cukup banyak, goreng telur yang sudah ditepungi hingga matang dan berwarna kuning kecoklatan.', 'Angkat, tiriskan, dan sajikan segera.', ],
                ],

                [
                    'name' => 'Udang Saus Mentega',
                    'image' => 'udang-saus-mentega.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 35,
                    'ingredients' => [
                        ['name' => 'Udang Kupas', 'amount' => 250, 'unit' => 'gr', 'notes' => 'Belah punggung dan buang kotorannya'],
                        ['name' => 'Blue Band Serbaguna', 'amount' => 4, 'unit' => 'sdm', 'notes' => 'Atau mentega/margarin lain'],
                        ['name' => 'Bawang Bombay', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Iris tipis'],
                        ['name' => 'Bawang Merah', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Cincang halus'],
                        ['name' => 'Bawang Putih', 'amount' => 2, 'unit' => 'siung', 'notes' => 'Cincang halus'],
                        ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Pisahkan bagian putih dan hijau'],
                        ['name' => 'Jahe', 'amount' => 3, 'unit' => 'cm', 'notes' => 'Geprek'],
                        ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Buang biji dan potong kecil'],
                        ['name' => 'Kecap Manis', 'amount' => 2, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Kecap Asin', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                        ['name' => 'Saus Tomat', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                    ],
                    'steps' => [ 'Cuci bersih udang yang sudah dikupas, belah punggungnya dan buang kotorannya. Sisihkan.', 'Lelehkan Blue Band Serbaguna dalam wajan, goreng udang hingga setengah matang atau berubah warna. Angkat dan sisihkan udang.', 'Gunakan wajan dan sisa mentega yang sama untuk menumis irisan bawang bombay, bagian putih daun bawang, bawang merah cincang, bawang putih cincang, tomat, dan jahe geprek.', 'Tumis semua bumbu hingga layu dan harum.', 'Masukkan kecap manis, kecap asin, saus tiram, saus tomat, dan kecap inggris. Aduk hingga semua saus tercampur rata.', 'Koreksi rasa, sesuaikan jika perlu.', 'Masukkan kembali udang yang sudah digoreng dan irisan daun bawang bagian hijau.', 'Aduk rata dan masak hingga bumbu meresap sempurna ke dalam udang.', 'Angkat dan sajikan udang saus mentega selagi hangat.', ],
                ],

                [
                    'name' => 'Bola-Bola Tahu Ayam Krispi',
                    'image' => 'bola-bola-tahu-ayam-krispi.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 40,
                    'ingredients' => [
                        ['name' => 'Tahu Putih', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Haluskan'],
                        ['name' => 'Palmia Margarin Serbaguna', 'amount' => 6, 'unit' => 'sdm', 'notes' => '3 sdm menumis, 3 sdm menggoreng'],
                        ['name' => 'Daging Ayam Cincang', 'amount' => 150, 'unit' => 'gr', 'notes' => null],
                        ['name' => 'Wortel', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Parut halus'],
                        ['name' => 'Tepung Maizena', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Untuk adonan'],
                        ['name' => 'Tepung Roti', 'amount' => 200, 'unit' => 'gr', 'notes' => 'Untuk baluran'],
                        ['name' => 'Telur', 'amount' => 3, 'unit' => 'butir', 'notes' => '1 untuk adonan, 2 untuk pencelup'],
                        ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Iris halus'],
                        ['name' => 'Minyak Sayur', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Untuk menggoreng'],
                        ['name' => 'Bawang Merah', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Lada', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk bumbu halus'],
                        ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk bumbu halus'],
                    ],
                    'steps' => [ 'Haluskan tahu dalam sebuah wadah besar.', 'Siapkan bumbu halus: ulek atau blender bawang merah, bawang putih, lada, dan garam.', 'Panaskan 3 sdm Palmia Margarin, tumis bumbu halus hingga harum.', 'Masukkan ayam cincang dan wortel parut ke dalam tumisan. Aduk dan masak hingga matang, lalu angkat.', 'Campurkan tumisan bumbu ke dalam tahu yang sudah dihaluskan. Aduk rata.', 'Tambahkan 1 butir telur, tepung maizena, dan irisan daun bawang ke dalam adonan. Aduk kembali hingga semua bahan tercampur sempurna.', 'Bentuk adonan menjadi bola-bola dengan ukuran sesuai selera hingga adonan habis.', 'Siapkan dua wadah: satu untuk 2 butir telur kocok, dan satu lagi untuk tepung roti.', 'Celupkan setiap bola tahu ke dalam kocokan telur, lalu gulingkan dan balur dengan tepung roti hingga tertutup rata.', 'Panaskan minyak sayur bersama 3 sdm sisa Palmia Margarin dengan api sedang.', 'Goreng bola-bola tahu hingga berwarna kuning kecoklatan dan matang.', 'Angkat, tiriskan, dan hidangkan selagi hangat dengan saus sambal atau mayones.', ],
                ],

                [
                    'name' => 'Martabak Telur Mini',
                    'image' => 'martabak-telur-mini.jpg',
                    'country_name' => 'Indonesia',
                    'cooking_time_minutes' => 35,
                    'ingredients' => [
                        ['name' => 'Kulit Lumpia', 'amount' => 20, 'unit' => 'lembar', 'notes' => null],
                        ['name' => 'Daging Cincang', 'amount' => 400, 'unit' => 'gr', 'notes' => null],
                        ['name' => 'Telur', 'amount' => 6, 'unit' => 'butir', 'notes' => 'Kocok lepas'],
                        ['name' => 'Daun Bawang', 'amount' => 6, 'unit' => 'batang', 'notes' => 'Iris halus'],
                        ['name' => 'Bawang Bombay', 'amount' => 125, 'unit' => 'gr', 'notes' => 'Cincang halus'],
                        ['name' => 'Bumbu Kari Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Lada Bubuk', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Garam', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                        ['name' => 'Margarin', 'amount' => 6, 'unit' => 'sdm', 'notes' => '2 sdm menumis, 4 sdm menggoreng'],
                        ['name' => 'Minyak Goreng', 'amount' => 100, 'unit' => 'ml', 'notes' => 'Untuk menggoreng'],
                    ],
                    'steps' => [ 'Panaskan 2 sdm margarin, tumis bawang bombai hingga harum dan layu.', 'Masukkan daging cincang ke dalam tumisan, aduk hingga daging berubah warna.', 'Taburkan bumbu kari, lada bubuk, dan garam. Aduk rata dan masak hingga daging matang dan mengering. Angkat dan sisihkan.', 'Dalam wadah terpisah, kocok lepas telur. Masukkan tumisan daging yang sudah dingin dan irisan daun bawang, aduk rata.', 'Ambil selembar kulit lumpia, letakkan dua sendok makan adonan isi di tengahnya.', 'Lipat kulit lumpia hingga menutupi isian, bentuk seperti amplop.', 'Panaskan 4 sdm margarin dan minyak goreng dalam wajan datar dengan api kecil.', 'Goreng martabak hingga kering dan berwarna kuning kecokelatan di kedua sisinya.', 'Angkat, tiriskan, dan hidangkan selagi hangat dengan acar mentimun dan cabai rawit.', ],
                ],

                [
            'name' => 'Gulai Kambing',
            'country_name' => 'Indonesia',
            'image' => 'gulai_kambing.jpg',
            'cooking_time_minutes' => 90,
            'ingredients' => [
                ['name' => 'Daging Kambing', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Potong-potong, bisa campur tulang'],
                ['name' => 'Santan Kental', 'amount' => 200, 'unit' => 'ml', 'notes' => 'Perasan pertama'],
                ['name' => 'Santan Encer', 'amount' => 800, 'unit' => 'ml', 'notes' => 'Perasan kedua'],
                ['name' => 'Serai', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Memarkan'],
                ['name' => 'Daun Jeruk', 'amount' => 4, 'unit' => 'buah', 'notes' => 'Sobek buang tulang daunnya'],
                ['name' => 'Daun Salam', 'amount' => 2, 'unit' => 'buah', 'notes' => null],
                ['name' => 'Lengkuas', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 3 cm, memarkan'],
                ['name' => 'Kayu Manis', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Sekitar 4 cm'],
                ['name' => 'Cengkeh', 'amount' => 5, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Minyak Goreng', 'amount' => 3, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],

                ['name' => 'Bawang Merah', 'amount' => 10, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Bawang Putih', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Cabai Merah Keriting', 'amount' => 10, 'unit' => 'buah', 'notes' => 'Sesuai selera, bumbu halus'],
                ['name' => 'Kemiri', 'amount' => 4, 'unit' => 'butir', 'notes' => 'Sangrai, bumbu halus'],
                ['name' => 'Kunyit', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Bakar, sekitar 3 cm, bumbu halus'],
                ['name' => 'Jahe', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 2 cm, bumbu halus'],
                ['name' => 'Ketumbar Bubuk', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Bumbu halus'],
                ['name' => 'Jintan', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Sangrai, bumbu halus'],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Bumbu halus'],
            ],
            'steps' => [
                'Haluskan semua bahan bumbu halus dengan sedikit minyak atau air.',
                'Panaskan minyak, tumis bumbu halus, serai, daun jeruk, daun salam, lengkuas, kayu manis, dan cengkeh hingga harum dan matang.',
                'Masukkan potongan daging kambing, aduk hingga berubah warna.',
                'Tuang santan encer, masak sambil diaduk perlahan agar santan tidak pecah.',
                'Masak hingga daging kambing mulai empuk.',
                'Tuang santan kental, bumbui dengan garam dan gula pasir.',
                'Masak kembali dengan api kecil sambil terus diaduk hingga daging benar-benar empuk, kuah mengental, dan berminyak.',
                'Koreksi rasa. Angkat dan sajikan Gulai Kambing dengan taburan bawang goreng.',
            ],
        ],
        [
            'name' => 'Rawon Sapi',
            'country_name' => 'Indonesia',
            'image' => 'rawon_sapi.jpg',
            'cooking_time_minutes' => 120,
            'ingredients' => [
                ['name' => 'Daging Sapi', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Bagian sandung lamur (brisket) atau sengkel, potong dadu'],
                ['name' => 'Air', 'amount' => 2000, 'unit' => 'ml', 'notes' => 'Untuk kuah kaldu'],
                ['name' => 'Daun Jeruk', 'amount' => 6, 'unit' => 'buah', 'notes' => 'Buang tulang daunnya'],
                ['name' => 'Serai', 'amount' => 3, 'unit' => 'batang', 'notes' => 'Memarkan'],
                ['name' => 'Daun Salam', 'amount' => 2, 'unit' => 'buah', 'notes' => null],
                ['name' => 'Lengkuas', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 3 cm, memarkan'],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Minyak Goreng', 'amount' => 4, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],

                ['name' => 'Kluwek', 'amount' => 4, 'unit' => 'buah', 'notes' => 'Ambil isinya, rendam air panas'],
                ['name' => 'Bawang Merah', 'amount' => 8, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Bawang Putih', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Kemiri', 'amount' => 4, 'unit' => 'butir', 'notes' => 'Sangrai, bumbu halus'],
                ['name' => 'Kunyit', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Bakar, sekitar 2 cm, bumbu halus'],
                ['name' => 'Jahe', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 1 cm, bumbu halus'],
                ['name' => 'Ketumbar Bubuk', 'amount' => 1.5, 'unit' => 'sdt', 'notes' => 'Bumbu halus'],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Bumbu halus'],
            ],
            'steps' => [
                'Rebus daging sapi dalam 2 liter air hingga empuk. Saring kaldunya, buang buihnya, dan potong-potong daging. Masukkan kembali daging ke air kaldu.',
                'Haluskan semua bahan bumbu halus (termasuk kluwek) hingga benar-benar halus.',
                'Panaskan minyak, tumis bumbu halus, daun jeruk, serai, daun salam, dan lengkuas hingga harum dan bumbu matang (berwarna lebih gelap dan berminyak).',
                'Masukkan tumisan bumbu ke dalam panci berisi rebusan daging dan kaldu.',
                'Tambahkan garam dan gula pasir. Aduk rata.',
                'Masak dengan api kecil hingga bumbu meresap sempurna ke dalam daging dan kuah sedikit mengental, sekitar 30-45 menit.',
                'Koreksi rasa. Sajikan rawon dengan pelengkap seperti tauge pendek, telur asin, dan sambal terasi.',
            ],
        ],
        [
            'name' => 'Babi Rica-Rica',
            'country_name' => 'Indonesia',
            'image' => 'babi_rica_rica.jpg',
            'cooking_time_minutes' => 60,
            'ingredients' => [
                ['name' => 'Daging Babi', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Bisa kapsim atau samcan, potong dadu'],
                ['name' => 'Air Jeruk Nipis', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Dari 1-2 buah jeruk nipis'],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kemangi', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Proxy untuk "ikat", petiki daunnya'],
                ['name' => 'Daun Bawang', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Iris kasar'],
                ['name' => 'Serai', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Ambil putihnya, memarkan'],
                ['name' => 'Daun Jeruk', 'amount' => 5, 'unit' => 'buah', 'notes' => 'Sobek-sobek'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk bumbu'],
                ['name' => 'Minyak Goreng', 'amount' => 4, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],
                ['name' => 'Air', 'amount' => 100, 'unit' => 'ml', 'notes' => 'Opsional'],

                ['name' => 'Cabai Rawit Merah', 'amount' => 20, 'unit' => 'buah', 'notes' => 'Sesuai selera, bumbu halus kasar'],
                ['name' => 'Cabai Merah Keriting', 'amount' => 10, 'unit' => 'buah', 'notes' => 'Bumbu halus kasar'],
                ['name' => 'Bawang Merah', 'amount' => 10, 'unit' => 'siung', 'notes' => 'Bumbu halus kasar'],
                ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => 'Bumbu halus kasar'],
                ['name' => 'Jahe', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 3 cm, bumbu halus kasar'],
                ['name' => 'Kunyit', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Bakar, sekitar 2 cm, bumbu halus kasar'],
            ],
            'steps' => [
                'Lumuri daging babi dengan air jeruk nipis dan 1 sdt garam. Diamkan 15 menit.',
                'Ulek atau blender kasar semua bahan bumbu halus (cabai, bawang, jahe, kunyit).',
                'Panaskan minyak, tumis bumbu halus, serai, dan daun jeruk hingga wangi dan matang.',
                'Masukkan daging babi, masak sambil diaduk hingga daging berubah warna dan kaku.',
                'Bumbui dengan garam dan gula pasir. Aduk rata.',
                'Tuang sedikit air (jika perlu) agar bumbu meresap dan daging matang. Masak hingga daging empuk dan air menyusut.',
                'Menjelang diangkat, masukkan daun bawang dan daun kemangi. Aduk cepat hingga layu.',
                'Koreksi rasa, angkat, dan sajikan.',
            ],
        ],
        [
            'name' => 'Bolu Pisang Kukus',
            'country_name' => 'Indonesia',
            'image' => 'bolu_pisang_kukus.jpg',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Pisang Ambon', 'amount' => 4, 'unit' => 'buah', 'notes' => 'Sangat matang, lumatkan (sekitar 200-250gr)'],
                ['name' => 'Tepung Terigu', 'amount' => 200, 'unit' => 'gr', 'notes' => 'Protein sedang'],
                ['name' => 'Gula Pasir', 'amount' => 150, 'unit' => 'gr', 'notes' => 'Bisa dikurangi jika pisang sangat manis'],
                ['name' => 'Telur', 'amount' => 4, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Minyak Goreng', 'amount' => 150, 'unit' => 'ml', 'notes' => 'Bisa diganti margarin cair'],
                ['name' => 'Soda Kue', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Baking Powder', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Vanili Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Opsional'],
            ],
            'steps' => [
                'Panaskan kukusan dengan api sedang. Lapisi tutup kukusan dengan kain bersih agar air tidak menetes.',
                'Olesi loyang dengan margarin dan taburi sedikit tepung. Sisihkan.',
                'Dalam wadah besar, kocok telur dan gula pasir menggunakan whisk atau mixer kecepatan rendah hingga gula larut.',
                'Masukkan pisang yang sudah dilumatkan. Aduk rata.',
                'Di wadah terpisah, campur tepung terigu, soda kue, baking powder, garam, dan vanili. Ayak campuran ini ke dalam adonan pisang.',
                'Aduk perlahan (teknik aduk balik) hingga tepung tercampur, jangan overmix.',
                'Tuang minyak goreng, aduk balik kembali hingga minyak menyatu dan tidak ada yang mengendap di dasar adonan.',
                'Tuang adonan ke dalam loyang yang sudah disiapkan.',
                'Kukus dalam kukusan yang sudah beruap penuh selama 30-35 menit dengan api sedang.',
                'Lakukan tes tusuk. Jika tidak ada adonan yang menempel, angkat bolu.',
                'Dinginkan bolu di cooling rack sebelum dipotong dan disajikan.',
            ],
        ],

[
            'name' => 'Sate Kambing Bumbu Kecap',
            'country_name' => 'Indonesia',
            'image' => 'sate_kambing.jpg',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Daging Kambing', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Potong dadu, campur lemak jika suka'],
                ['name' => 'Tusuk Sate', 'amount' => 20, 'unit' => 'batang', 'notes' => 'Rendam dalam air agar tidak hangus'],
                ['name' => 'Kecap Manis', 'amount' => 12, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Margarin', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Cairkan, untuk olesan'],
                
                ['name' => 'Bawang Merah', 'amount' => 13, 'unit' => 'siung', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus marinasi'],
                ['name' => 'Ketumbar Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk bumbu halus marinasi'],
                ['name' => 'Merica Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk bumbu halus marinasi'],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk bumbu halus marinasi'],
                ['name' => 'Air Asam Jawa', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Opsional, bumbu halus marinasi'],
                ['name' => 'Cabai Rawit', 'amount' => 10, 'unit' => 'buah', 'notes' => 'Iris, untuk sambal kecap (sesuai selera)'],
                ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong dadu, untuk sambal kecap'],
                ['name' => 'Jeruk Limau', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Peras airnya, untuk sambal kecap'],
            ],
            'steps' => [
                'Haluskan bawang merah, bawang putih, ketumbar, merica, garam, dan air asam jawa.',
                'Campur bumbu halus dengan 5 sdm kecap manis. Lumurkan pada daging kambing yang sudah dipotong.',
                'Marinasi daging minimal 30 menit agar bumbu meresap.',
                'Tusuk daging pada tusukan sate.',
                'Siapkan bumbu olesan: campur sisa bumbu marinasi dengan 2 sdm kecap manis dan 2 sdm margarin cair.',
                'Bakar sate di atas bara api (arang) sambil dibolak-balik.',
                'Olesi sate dengan bumbu olesan secara berkala hingga matang dan sedikit gosong di pinggirnya.',
                'Siapkan sambal kecap: campur semua bahan pelengkap (kecap, irisan bawang, cabai, tomat, dan air jeruk).',
                'Sajikan sate kambing panas-panas dengan sambal kecap.',
            ],
        ],
        [
            'name' => 'Semur Daging Sapi Kentang',
            'country_name' => 'Indonesia',
            'image' => 'semur_daging.jpg',
            'cooking_time_minutes' => 90,
            'ingredients' => [
                ['name' => 'Daging Sapi', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Pilih bagian sengkel atau sandung lamur, potong dadu'],
                ['name' => 'Kentang', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Ukuran sedang, kupas, potong dadu'],
                ['name' => 'Kecap Manis', 'amount' => 8, 'unit' => 'sdm', 'notes' => 'Sesuai selera'],
                ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong menjadi 4 bagian'],
                ['name' => 'Air', 'amount' => 700, 'unit' => 'ml', 'notes' => 'Bisa pakai air kaldu rebusan daging'],
                ['name' => 'Minyak Goreng', 'amount' => 3, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],
                ['name' => 'Daun Salam', 'amount' => 2, 'unit' => 'buah', 'notes' => null],
                ['name' => 'Lengkuas', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 3 cm, memarkan'],
                ['name' => 'Serai', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Memarkan'],
                ['name' => 'Pala Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Lada Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Opsional, penyeimbang rasa'],
                
                ['name' => 'Bawang Merah', 'amount' => 8, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Kemiri', 'amount' => 3, 'unit' => 'butir', 'notes' => 'Sangrai, untuk bumbu halus'],
            ],
            'steps' => [
                'Opsional: Rebus daging sapi hingga setengah empuk. Sisihkan air kaldunya. Tiriskan daging.',
                'Haluskan bawang merah, bawang putih, dan kemiri.',
                'Panaskan minyak, tumis bumbu halus, daun salam, lengkuas, dan serai hingga harum dan matang.',
                'Masukkan potongan daging sapi, aduk hingga berubah warna.',
                'Tambahkan kecap manis, pala bubuk, lada bubuk, garam, dan gula pasir. Aduk rata.',
                'Tuangkan air (atau air kaldu). Masak hingga mendidih.',
                'Tutup wajan dan masak dengan api kecil hingga daging empuk (sekitar 45-60 menit).',
                'Masukkan potongan kentang dan tomat.',
                'Masak kembali hingga kentang matang dan kuah mengental.',
                'Koreksi rasa. Sajikan semur daging dengan taburan bawang goreng.',
            ],
        ],
        [
            'name' => 'Babi Panggang Merah',
            'country_name' => 'Indonesia',
            'image' => 'babi_panggang_merah.jpg',
            'cooking_time_minutes' => 75,
            'ingredients' => [
                ['name' => 'Daging Babi', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Bagian kapsim atau samcan (perut)'],
                ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => 'Haluskan, untuk marinasi'],
                ['name' => 'Madu', 'amount' => 4, 'unit' => 'sdm', 'notes' => '3 sdm u/ marinasi, 1 sdm u/ olesan'],
                ['name' => 'Kecap Asin', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk marinasi'],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk marinasi'],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk marinasi'],
                ['name' => 'Bumbu Ngohiong', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Wajib ada, untuk marinasi'],
                ['name' => 'Angkak', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Haluskan, rendam air panas. (Opsional, untuk warna merah)'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk marinasi'],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk marinasi'],
                ['name' => 'Air', 'amount' => 50, 'unit' => 'ml', 'notes' => 'Untuk sisa bumbu/olesan'],
            ],
            'steps' => [
                'Siapkan daging, potong memanjang jika terlalu tebal.',
                'Dalam wadah, campur semua bahan marinasi: bawang putih halus, 3 sdm madu, kecap asin, saus tiram, minyak wijen, bumbu ngohiong, angkak (yang sudah dihaluskan dan dilarutkan), gula, dan garam.',
                'Lumuri daging babi secara merata dengan bumbu marinasi. Tutup wadah dan simpan di kulkas minimal 4 jam atau semalaman.',
                'Panaskan oven di suhu 200°C. Siapkan loyang yang dialasi aluminium foil.',
                'Letakkan rak kawat di atas loyang, lalu taruh daging babi di atas rak kawat (agar panggangan merata dan tidak terendam minyak).',
                'Panggang selama 20 menit. Sambil menunggu, campur sisa bumbu marinasi dengan 1 sdm madu dan 50ml air untuk bahan olesan.',
                'Keluarkan daging, balik, lalu olesi seluruh permukaan dengan bahan olesan.',
                'Panggang lagi selama 20 menit.',
                'Keluarkan, olesi sekali lagi. Panggang 10-15 menit terakhir atau hingga terkaramelisasi (sedikit gosong di pinggir).',
                'Angkat, dinginkan sebentar, lalu potong-potong dan sajikan.',
            ],
        ],
        [
            'name' => 'Pisang Goreng Krispi',
            'country_name' => 'Indonesia',
            'image' => 'pisang_goreng_krispi.jpg',
            'cooking_time_minutes' => 30,
            'ingredients' => [
                ['name' => 'Pisang Uli', 'amount' => 8, 'unit' => 'buah', 'notes' => 'Bisa pisang raja, belah 2 atau 4 memanjang'],
                ['name' => 'Minyak Goreng', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Untuk menggoreng (deep fry)'],
                
                ['name' => 'Tepung Terigu', 'amount' => 10, 'unit' => 'sdm', 'notes' => 'Sekitar 100gr, protein sedang'],
                ['name' => 'Tepung Beras', 'amount' => 3, 'unit' => 'sdm', 'notes' => 'Sekitar 30gr, kunci krispi'],
                ['name' => 'Tepung Maizena', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Sesuai selera'],
                ['name' => 'Garam', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Vanili Bubuk', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => 'Opsional'],
                ['name' => 'Air', 'amount' => 150, 'unit' => 'ml', 'notes' => 'Air es/dingin, tuang sedikit-sedikit'],
                ['name' => 'Margarin', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Cairkan'],
            ],
            'steps' => [
                'Dalam wadah, campur semua bahan kering: tepung terigu, tepung beras, maizena, gula pasir, garam, dan vanili bubuk.',
                'Tuang air dingin sedikit demi sedikit sambil diaduk hingga mendapatkan kekentalan adonan yang pas (tidak terlalu encer, tidak terlalu kental).',
                'Masukkan margarin cair ke dalam adonan. Aduk rata. Ini membantu menambah kerenyahan.',
                'Panaskan minyak goreng yang banyak dengan api sedang.',
                'Celupkan potongan pisang ke dalam adonan tepung hingga seluruh permukaan tertutup rata.',
                'Segera masukkan pisang ke dalam minyak panas.',
                'Goreng hingga pisang berwarna kuning keemasan dan krispi.',
                'Angkat, tiriskan minyaknya.',
                'Sajikan selagi hangat, bisa ditambahkan topping keju parut atau kental manis jika suka.',
            ],
        ],
        [
            'name' => 'Sempol Babi Jumbo',
            'image' => 'sempol_babi_jumbo.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 50,
            'ingredients' => [
                ['name' => 'Babi Giling', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Bagian kapsin'],
                ['name' => 'Bawang Putih', 'amount' => 6, 'unit' => 'siung', 'notes' => 'Untuk adonan'],
                ['name' => 'Bawang Merah', 'amount' => 6, 'unit' => 'siung', 'notes' => 'Untuk adonan'],
                ['name' => 'Telur', 'amount' => 3, 'unit' => 'butir', 'notes' => null], // Total dari 2 (adonan) + 1 (baluran)
                ['name' => 'Wortel', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Parut lalu cincang'],
                ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Iris halus'],
                ['name' => 'Santan Kental', 'amount' => 60, 'unit' => 'ml', 'notes' => null],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 1.5, 'unit' => 'sdt', 'notes' => 'Untuk adonan'],
                ['name' => 'Kaldu Jamur Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Opsional'],
                ['name' => 'Lada Putih Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Tepung Terigu Serbaguna', 'amount' => 100, 'unit' => 'gr', 'notes' => null],
                ['name' => 'Tepung Tapioka', 'amount' => 200, 'unit' => 'gr', 'notes' => null],
                ['name' => 'Stick Ice Cream', 'amount' => 30, 'unit' => 'batang', 'notes' => 'Rebus dan keringkan'],
                ['name' => 'Air', 'amount' => 1530, 'unit' => 'ml', 'notes' => null], // Total dari 1500ml + 2sdm (30ml)
                ['name' => 'Minyak Goreng', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Untuk menggoreng'],
            ],
            'steps' => [
                'Masukkan babi giling, bawang putih, bawang merah, dan 2 butir telur ke dalam chopper. Giling hingga halus.', // Langkah tetap menyebut 2 butir
                'Pindahkan adonan ke mangkuk besar. Masukkan wortel parut cincang dan irisan daun bawang.',
                'Tambahkan santan kental, saus tiram, minyak wijen, garam, kaldu jamur, lada, dan gula. Aduk rata.',
                'Masukkan tepung terigu, aduk rata. Masukkan tepung tapioka, aduk kembali hingga semua bahan tercampur sempurna.',
                'Didihkan air (sekitar 1500ml) dalam panci.', // Langkah tetap menyebut 1500ml
                'Ambil adonan secukupnya, lilitkan dan padatkan pada stik es krim hingga berbentuk lonjong.',
                'Langsung masukkan sempol yang sudah dibentuk ke dalam air mendidih.',
                'Rebus sempol hingga matang (tandanya mengapung). Angkat dan tiriskan, biarkan dingin.',
                'Siapkan baluran: Kocok lepas 1 butir telur dengan 2 sdm air.', // Langkah tetap menyebut 1 butir dan 2 sdm
                'Panaskan minyak yang banyak untuk menggoreng.',
                'Celupkan sempol yang sudah dingin ke dalam kocokan telur.',
                'Goreng sempol dengan minyak panas hingga kuning kecoklatan. Angkat dan tiriskan.',
                'Sajikan Sempol Babi Jumbo selagi hangat.',
            ],
        ],
        [
            'name' => 'Sop Kambing Bening',
            'image' => 'sop_kambing_bening.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 75,
            'ingredients' => [
                ['name' => 'Daging Kambing', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Potong dadu, campur tulang iga'],
                ['name' => 'Air', 'amount' => 1500, 'unit' => 'ml', 'notes' => 'Untuk merebus'],
                ['name' => 'Kentang', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Kupas, potong dadu'],
                ['name' => 'Wortel', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Potong bulat'],
                ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong jadi 6 bagian'],
                ['name' => 'Daun Bawang', 'amount' => 2, 'unit' => 'batang', 'notes' => null], // 1 untuk rebus, 1 untuk tabur
                ['name' => 'Seledri', 'amount' => 2, 'unit' => 'batang', 'notes' => null], // 1 untuk rebus, 1 untuk tabur
                ['name' => 'Bawang Putih', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Pala Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kapulaga', 'amount' => 3, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Cengkeh', 'amount' => 3, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Kayu Manis', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Sekitar 3-4 cm'],
                ['name' => 'Minyak Goreng', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],
                ['name' => 'Bawang Goreng', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk taburan'],
            ],
            'steps' => [
                'Rebus daging kambing dalam 1500ml air hingga mendidih. Buang buih kotoran, lalu kecilkan api dan rebus hingga empuk (sekitar 45-60 menit).',
                'Panaskan minyak, tumis bawang putih halus, kapulaga, cengkeh, dan kayu manis hingga harum.',
                'Masukkan tumisan bumbu ke dalam panci rebusan daging.',
                'Masukkan kentang dan wortel. Masak hingga sayuran empuk.',
                'Bumbui dengan garam, gula pasir, pala bubuk, dan merica bubuk.',
                'Masukkan 1 batang daun bawang dan 1 batang seledri yang dipotong besar.',
                'Menjelang diangkat, masukkan potongan tomat dan 1 batang irisan daun bawang & seledri.',
                'Koreksi rasa. Sajikan sop kambing panas dengan taburan bawang goreng.',
            ],
        ],
        [
            'name' => 'Sop Buntut Sapi',
            'image' => 'sop_buntut.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 180,
            'ingredients' => [
                ['name' => 'Buntut Sapi', 'amount' => 1, 'unit' => 'kg', 'notes' => 'Potong-potong, cuci bersih'],
                ['name' => 'Air', 'amount' => 2000, 'unit' => 'ml', 'notes' => 'Untuk kaldu'],
                ['name' => 'Wortel', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Impor, potong bulat tebal'],
                ['name' => 'Kentang', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Potong dadu besar'],
                ['name' => 'Bawang Putih', 'amount' => 6, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Bawang Bombay', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Iris kasar'],
                ['name' => 'Pala Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Cengkeh', 'amount' => 4, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Kayu Manis', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Sekitar 4 cm'],
                ['name' => 'Daun Bawang', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Potong 2 cm'],
                ['name' => 'Seledri', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Ikat simpul'],
                ['name' => 'Tomat', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong 6 bagian'],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Sesuai selera'],
                ['name' => 'Margarin', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk menumis bumbu'],
            ],
            'steps' => [
                'Rebus buntut sapi dalam air mendidih selama 10 menit (blanching). Buang air rebusan pertama.',
                'Rebus kembali buntut dengan 2000ml air bersih. Masak dengan api kecil hingga buntut empuk (bisa 2-3 jam). Sisihkan kaldunya.',
                'Panaskan margarin. Tumis bawang putih halus, bawang bombay, cengkeh, kayu manis, pala bubuk, dan merica bubuk hingga harum.',
                'Masukkan tumisan bumbu ke dalam panci kaldu dan buntut. Didihkan kembali.',
                'Masukkan kentang dan wortel, masak hingga sayuran matang.',
                'Tambahkan garam dan gula pasir. Aduk rata.',
                'Menjelang diangkat, masukkan daun bawang, seledri ikat, dan potongan tomat.',
                'Masak sebentar hingga tomat sedikit layu. Koreksi rasa.',
                'Sajikan sop buntut dengan taburan bawang goreng dan emping.',
            ],
        ],
        [
            'name' => 'Es Pisang Ijo',
            'image' => 'es_pisang_ijo.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 60,
            'ingredients' => [
                ['name' => 'Pisang Raja', 'amount' => 6, 'unit' => 'buah', 'notes' => 'Kukus hingga matang'],
                // --- REVISI: Bahan duplikat digabung ---
                ['name' => 'Tepung Beras', 'amount' => 210, 'unit' => 'gr', 'notes' => null], // 150gr kulit + 60gr bubur
                ['name' => 'Santan', 'amount' => 900, 'unit' => 'ml', 'notes' => null], // 400ml kulit + 500ml bubur
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => null], // 0.5sdt kulit + 0.5sdt bubur
                // --- Bahan unik ---
                ['name' => 'Tepung Terigu', 'amount' => 50, 'unit' => 'gr', 'notes' => 'Protein sedang'],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk adonan kulit'],
                ['name' => 'Pasta Pandan', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Atau pewarna hijau'],
                ['name' => 'Daun Pandan', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Ikat simpul, untuk bubur'],
                ['name' => 'Sirup Cocopandan', 'amount' => 150, 'unit' => 'ml', 'notes' => 'Sirup merah'],
                ['name' => 'Susu Kental Manis Putih', 'amount' => 5, 'unit' => 'sdm', 'notes' => 'Sesuai selera'],
                ['name' => 'Es Batu', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Serut atau hancurkan'],
            ],
            'steps' => [
                'Adonan Kulit: Campur 150gr tepung beras, 50gr tepung terigu, 1 sdm gula, 0.5 sdt garam, dan 400ml santan. Aduk rata.',
                'Tambahkan pasta pandan. Masak di atas api kecil sambil diaduk hingga adonan mengental dan kalis. Angkat dan dinginkan.',
                'Ambil sedikit adonan kulit, pipihkan. Letakkan 1 buah pisang raja kukus di atasnya, lalu bungkus pisang hingga tertutup rata. Ulangi.',
                'Kukus pisang yang sudah dibungkus adonan selama 15 menit. Angkat dan dinginkan.',
                'Bubur Sumsum: Campur 60gr tepung beras, 500ml santan, 2 batang daun pandan, dan 0.5 sdt garam. Aduk rata.',
                'Masak adonan bubur di api kecil sambil terus diaduk hingga mengental dan meletup-letup. Angkat.',
                'Penyajian: Potong-potong pisang ijo. Letakkan di mangkuk.',
                'Tambahkan bubur sumsum, es batu serut, sirup cocopandan, dan susu kental manis.',
                'Es Pisang Ijo siap disajikan.',
            ],
        ],
        [
            'name' => 'Krengsengan Kambing',
            'image' => 'krengsengan_kambing.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 60,
            'ingredients' => [
                ['name' => 'Daging Kambing', 'amount' => 500, 'unit' => 'gr', 'notes' => 'Potong dadu'],
                ['name' => 'Kecap Manis', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Petis Udang', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Opsional, tapi khas'],
                ['name' => 'Tomat', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Potong kasar'],
                ['name' => 'Air', 'amount' => 300, 'unit' => 'ml', 'notes' => 'Atau air kaldu'],
                ['name' => 'Minyak Goreng', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk menumis'],
                ['name' => 'Bawang Merah', 'amount' => 8, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Cabai Rawit', 'amount' => 5, 'unit' => 'buah', 'notes' => 'Sesuai selera, bumbu halus'],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Bumbu halus'],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Bawang Goreng', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk taburan'],
            ],
            'steps' => [
                'Haluskan bawang merah, bawang putih, cabai rawit, dan merica.',
                'Panaskan minyak, tumis bumbu halus hingga harum dan matang.',
                'Masukkan potongan daging kambing, aduk hingga berubah warna.',
                'Tambahkan kecap manis dan petis udang. Aduk rata.',
                'Tuangkan air, bumbui dengan garam. Aduk rata.',
                'Masak dengan api kecil (ungkep) hingga daging empuk dan kuah mengental.',
                'Menjelang diangkat, masukkan potongan tomat. Aduk sebentar hingga tomat layu.',
                'Koreksi rasa. Sajikan krengsengan kambing dengan taburan bawang goreng.',
            ],
        ],
        [
            'name' => 'Iga Bakar Kecap',
            'image' => 'iga_bakar_kecap.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 150,
            'ingredients' => [
                ['name' => 'Iga Sapi', 'amount' => 1, 'unit' => 'kg', 'notes' => 'Potong-potong'],
                ['name' => 'Air', 'amount' => 1500, 'unit' => 'ml', 'notes' => 'Untuk merebus'],
                ['name' => 'Bawang Merah', 'amount' => 10, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Bawang Putih', 'amount' => 6, 'unit' => 'siung', 'notes' => 'Untuk bumbu halus'],
                ['name' => 'Ketumbar Bubuk', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Bumbu halus'],
                ['name' => 'Jintan', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Bumbu halus, sangrai'],
                ['name' => 'Jahe', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Sekitar 2 cm, bumbu halus'],
                ['name' => 'Air Asam Jawa', 'amount' => 3, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Serai', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Memarkan'],
                ['name' => 'Daun Salam', 'amount' => 3, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
                ['name' => 'Gula Merah', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Sisir halus'],
                ['name' => 'Garam', 'amount' => 2, 'unit' => 'sdt', 'notes' => null],
                // --- REVISI: Bahan duplikat (5 sdm ungkep + 3 sdm olesan) digabung ---
                ['name' => 'Kecap Manis', 'amount' => 8, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Margarin', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Cairkan'],
            ],
            'steps' => [
                'Rebus iga sapi dalam air hingga empuk (bisa gunakan presto). Ambil 500ml air kaldu sisa rebusan, sisihkan.',
                'Haluskan bawang merah, bawang putih, ketumbar, jintan, dan jahe.',
                'Tumis bumbu halus, serai, dan daun salam hingga harum.',
                'Masukkan iga, air kaldu, air asam jawa, gula merah, garam, dan 5 sdm kecap manis.',
                'Ungkep (masak) dengan api kecil hingga air menyusut dan bumbu meresap. Simpan sisa bumbu ungkep.',
                'Siapkan bumbu olesan: Campur sisa bumbu ungkep, 3 sdm kecap manis, dan margarin cair.',
                'Bakar iga di atas bara api atau teflon sambil diolesi bumbu olesan.',
                'Bakar hingga kedua sisi terkaramelisasi. Angkat dan sajikan.',
            ],
        ],
        [
            'name' => 'Babi Asam Manis',
            'image' => 'babi_asam_manis.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Daging Babi', 'amount' => 300, 'unit' => 'gr', 'notes' => 'Kapsim, potong dadu'],
                ['name' => 'Bawang Putih', 'amount' => 4, 'unit' => 'siung', 'notes' => null],
                ['name' => 'Kecap Asin', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => 'Kocok lepas'],
                ['name' => 'Tepung Maizena', 'amount' => 6, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Goreng', 'amount' => 500, 'unit' => 'ml', 'notes' => 'Untuk menggoreng'],
                ['name' => 'Bawang Bombay', 'amount' => 0.5, 'unit' => 'buah', 'notes' => 'Iris memanjang'],
                ['name' => 'Wortel', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong korek api'],
                ['name' => 'Timun', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Buang biji, potong korek api'],
                ['name' => 'Saus Tomat', 'amount' => 4, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Saus Sambal', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Opsional'],
                ['name' => 'Gula Pasir', 'amount' => 2, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Cuka Makan', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Air', 'amount' => 200, 'unit' => 'ml', 'notes' => 'Untuk saus'],
            ],
            'steps' => [
                'Marinasi daging babi dengan 1 siung bawang putih halus, kecap asin, dan minyak wijen. Diamkan 15 menit.',
                'Celupkan babi ke kocokan telur, lalu balur rata dengan 5 sdm tepung maizena.',
                'Goreng babi dalam minyak panas hingga matang dan krispi. Angkat, tiriskan.',
                'Saus: Tumis 3 siung bawang putih cincang dan bawang bombay hingga harum.',
                'Masukkan wortel dan timun, tumis sebentar.',
                'Masukkan saus tomat, saus sambal, gula, garam, cuka, dan air. Aduk rata.',
                'Kentalkan saus dengan larutan 1 sdm tepung maizena. Masak hingga meletup-letup.',
                'Masukkan babi goreng, aduk cepat hingga saus merata.',
                'Angkat dan sajikan Babi Asam Manis segera.',
            ],
        ],
        [
            'name' => 'Dimsum Ayam Original',
            'image' => 'dimsum_ayam_original.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Ayam Giling', 'amount' => 250, 'unit' => 'gr', 'notes' => 'Bagian paha lebih juicy'],
                ['name' => 'Tepung Tapioka', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Putih Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Kecap Asin', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kulit Dimsum', 'amount' => 15, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
            ],
            'steps' => [
                'Dalam wadah besar, campur ayam giling dengan bawang putih, putih telur, saus tiram, minyak wijen, kecap asin, garam, gula, dan merica.',
                'Aduk adonan hingga lengket dan tercampur rata.',
                'Masukkan tepung tapioka, aduk kembali hingga benar-benar menyatu.',
                'Ambil selembar kulit dimsum, letakkan 1 sdm adonan di tengahnya.',
                'Katkan dan lipat sisi-sisinya hingga membentuk mangkuk, biarkan bagian atasnya terbuka.',
                'Olesi alas kukusan dengan minyak agar tidak lengket.',
                'Kukus dimsum dalam kukusan yang sudah panas selama 20-25 menit atau hingga matang.',
                'Sajikan hangat dengan saus sambal.',
            ],
        ],
        [
            'name' => 'Dimsum Ayam Jamur',
            'image' => 'dimsum_ayam_jamur.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Ayam Giling', 'amount' => 250, 'unit' => 'gr', 'notes' => 'Bagian paha'],
                ['name' => 'Jamur Kuping', 'amount' => 40, 'unit' => 'gr', 'notes' => 'Rendam, cincang kasar'],
                ['name' => 'Tepung Tapioka', 'amount' => 2, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 2, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Bawang Bombay', 'amount' => 0.5, 'unit' => 'buah', 'notes' => 'Cincang halus'],
                ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Iris halus'],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 0.25, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kulit Dimsum', 'amount' => 15, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
            ],
            'steps' => [
                'Campur bawang putih, bawang bombay, dan daun bawang dengan ayam giling. Aduk rata.',
                'Masukkan jamur kuping cincang, aduk kembali.',
                'Tambahkan tepung tapioka, saus tiram, minyak wijen, gula, garam, dan merica ke adonan. Aduk rata hingga lengket.',
                'Ambil selembar kulit dimsum, beri isian secukupnya (sekitar 1 sdm).',
                'Rekatkan pinggirannya dan bentuk sesuai selera, biarkan bagian atas terbuka.',
                'Kukus dimsum di atas kukusan yang sudah dioles minyak selama 25 menit hingga matang.',
                'Angkat dan sajikan.',
            ],
        ],
        [
            'name' => 'Dimsum Ayam Wortel',
            'image' => 'dimsum_ayam_wortel.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Ayam Giling', 'amount' => 250, 'unit' => 'gr', 'notes' => null],
                // --- REVISI: 80gr adonan + 20gr topping digabung ---
                ['name' => 'Wortel', 'amount' => 100, 'unit' => 'gr', 'notes' => null],
                ['name' => 'Tepung Tapioka', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 2, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Lada bubuk'],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Kecap Asin', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Daun Bawang', 'amount' => 1, 'unit' => 'batang', 'notes' => 'Iris halus'],
                ['name' => 'Kulit Dimsum', 'amount' => 15, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
            ],
            'steps' => [
                'Parut wortel. Sisihkan sekitar 20gr untuk topping, 80gr sisanya untuk adonan.',
                'Campur ayam giling, 80gr parutan wortel, bawang putih, telur, daun bawang, dan semua bumbu (garam, gula, merica, minyak wijen, kecap asin).',
                'Aduk rata adonan, lalu masukkan tepung tapioka. Aduk kembali hingga tercampur sempurna.',
                'Ambil selembar kulit dimsum, isi dengan 1 sdm adonan.',
                'Bentuk adonan dimsum, lalu beri sisa parutan wortel (20gr) di atasnya sebagai topping.',
                'Kukus selama 20-25 menit dalam kukusan yang sudah panas dan diolesi minyak.',
                'Sajikan selagi hangat.',
            ],
        ],
        [
            'name' => 'Dimsum Ayam Mozzarella',
            'image' => 'dimsum_ayam_mozzarella.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Ayam Giling', 'amount' => 250, 'unit' => 'gr', 'notes' => null],
                ['name' => 'Keju Mozzarella', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Potong dadu kecil'],
                ['name' => 'Tepung Tapioka', 'amount' => 3, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Putih Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 3, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kulit Dimsum', 'amount' => 15, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
            ],
            'steps' => [
                'Campur ayam giling, bawang putih, putih telur, saus tiram, minyak wijen, garam, dan merica. Aduk rata.',
                'Masukkan tepung tapioka, aduk kembali hingga adonan lengket dan menyatu.',
                'Ambil selembar kulit dimsum, letakkan 1 sdt adonan.',
                'Selipkan 1-2 potong dadu keju mozzarella di tengah adonan.',
                'Bungkus kembali dengan 1 sdt adonan di atasnya, lalu rapatkan kulit dimsum.',
                'Bentuk dimsum, biarkan bagian atas terbuka sedikit jika suka, atau tutup rapat.',
                'Kukus selama 20-25 menit hingga matang dan keju di dalamnya meleleh.',
                'Sajikan segera selagi keju masih lumer.',
            ],
        ],
        [
            'name' => 'Dimsum Ayam Udang',
            'image' => 'dimsum_ayam_udang.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Ayam Giling', 'amount' => 200, 'unit' => 'gr', 'notes' => 'Bagian paha'],
                ['name' => 'Udang Kupas', 'amount' => 50, 'unit' => 'gr', 'notes' => 'Cincang kasar'],
                ['name' => 'Tepung Tapioka', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Putih Telur', 'amount' => 1, 'unit' => 'butir', 'notes' => null],
                ['name' => 'Bawang Putih', 'amount' => 2, 'unit' => 'siung', 'notes' => 'Haluskan'],
                ['name' => 'Saus Tiram', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Minyak Wijen', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Kecap Asin', 'amount' => 1, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Gula Pasir', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Merica Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Kulit Dimsum', 'amount' => 15, 'unit' => 'buah', 'notes' => 'Proxy untuk "lembar"'],
                ['name' => 'Wortel', 'amount' => 20, 'unit' => 'gr', 'notes' => 'Parut, untuk topping'],
            ],
            'steps' => [
                'Dalam food processor, giling ayam, bawang putih, dan putih telur hingga setengah halus.',
                'Pindahkan ke mangkuk. Masukkan udang cincang (sisakan sedikit untuk topping jika suka).',
                'Tambahkan saus tiram, minyak wijen, kecap asin, garam, gula, dan merica. Aduk adonan hingga lengket.',
                'Masukkan tepung tapioka, aduk rata.',
                'Ambil selembar kulit dimsum, isi dengan adonan. Beri topping wortel parut di atasnya.',
                'Susun di kukusan yang sudah diolesi minyak.',
                'Kukus selama 20-25 menit hingga matang sempurna.',
                'Sajikan hangat.',
            ],
        ],
        [
            'name' => 'Terang Bulan Keju',
            'image' => 'terang_bulan_keju.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Tepung Terigu', 'amount' => 250, 'unit' => 'gr', 'notes' => 'Protein sedang'],
                // --- REVISI: 5 sdm (adonan) + 3 sdm (tabur) ---
                ['name' => 'Gula Pasir', 'amount' => 8, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Baking Powder', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                // --- REVISI: 300ml (adonan) + 3 sdm/45ml (pelarut) ---
                ['name' => 'Air', 'amount' => 345, 'unit' => 'ml', 'notes' => null],
                ['name' => 'Ragi Instan', 'amount' => 1, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Soda Kue', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => null],
                ['name' => 'Telur', 'amount' => 2, 'unit' => 'butir', 'notes' => 'Kocok lepas'],
                // --- REVISI: 2 sdm (adonan) + 3 sdm (olesan) ---
                ['name' => 'Margarin', 'amount' => 5, 'unit' => 'sdm', 'notes' => null],
                ['name' => 'Susu Kental Manis Putih', 'amount' => 3, 'unit' => 'sdm', 'notes' => 'Sesuai selera'],
                ['name' => 'Keju Cheddar', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Parut'],
            ],
            'steps' => [
                'Dalam wadah, campur tepung terigu, 5 sdm gula pasir, garam, baking powder, dan ragi instan. Aduk rata.',
                'Tuang 300ml air sedikit demi sedikit sambil diaduk (whisk) hingga adonan licin dan tidak bergerindil.',
                'Tutup wadah, diamkan adonan selama 15 menit.',
                'Setelah 15 menit, masukkan kocokan telur dan 2 sdm margarin cair. Aduk rata.',
                'Larutkan soda kue dengan 3 sdm air, tuang ke dalam adonan, aduk cepat hingga rata.',
                'Panaskan teflon (loyang martabak) dengan api kecil hingga benar-benar panas.',
                'Tuang adonan, biarkan adonan membentuk pinggiran di sisi teflon.',
                'Masak hingga adonan mulai berlubang-lubang. Taburi 3 sdm gula pasir di permukaannya.',
                'Tutup teflon, masak dengan api sangat kecil hingga seluruh permukaan matang (tidak basah).',
                'Angkat terang bulan, pindahkan ke talenan. Segera olesi permukaannya dengan 3 sdm margarin selagi panas.',
                'Taburi keju cheddar parut secara merata di setengah bagian, lalu beri susu kental manis.',
                'Lipat martabak, olesi bagian kulit luarnya dengan sisa margarin. Potong-potong dan sajikan.',
            ],
        ],
        [
            'name' => 'Salad Pasta ala Yunani',
            'image' => 'salad_pasta_yunani.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 25,
            'ingredients' => [
                ['name' => 'Pasta Kering', 'amount' => 400, 'unit' => 'gr', 'notes' => 'Bentuk spiral atau penne'],
                ['name' => 'Timun', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Potong dadu'],
                ['name' => 'Tomat Ceri', 'amount' => 150, 'unit' => 'gr', 'notes' => 'Belah dua'],
                ['name' => 'Bawang Bombay Merah', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Iris tipis'],
                ['name' => 'Zaitun Hitam', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Buang biji, bisa belah dua'],
                ['name' => 'Keju Feta', 'amount' => 100, 'unit' => 'gr', 'notes' => 'Remukkan kasar'],
                ['name' => 'Paprika Hijau', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Buang biji, potong dadu'],
                ['name' => 'Minyak Zaitun', 'amount' => 6, 'unit' => 'sdm', 'notes' => 'Extra virgin, untuk saus'],
                ['name' => 'Cuka Anggur Merah', 'amount' => 3, 'unit' => 'sdm', 'notes' => 'Red wine vinegar, untuk saus'],
                ['name' => 'Bawang Putih', 'amount' => 1, 'unit' => 'siung', 'notes' => 'Haluskan, untuk saus'],
                ['name' => 'Oregano Kering', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk saus'],
                ['name' => 'Garam', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Sesuai selera, untuk saus'],
                ['name' => 'Lada Hitam Bubuk', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Sesuai selera, untuk saus'],
            ],
            'steps' => [
                'Masak pasta sesuai petunjuk di kemasan. Tiriskan, siram dengan air dingin, dan beri sedikit minyak agar tidak lengket. Sisihkan.',
                'Selagi menunggu pasta, siapkan sayuran: potong dadu timun, belah dua tomat ceri, iris tipis bawang bombay merah, dan potong dadu paprika hijau.',
                'Siapkan saus: Dalam toples atau mangkuk kecil, campur minyak zaitun, cuka anggur merah, bawang putih halus, dan oregano kering.',
                'Bumbui saus dengan garam dan lada hitam, lalu kocok atau aduk hingga tercampur rata.',
                'Dalam sebuah mangkuk saji besar, gabungkan pasta yang sudah dingin dengan timun, tomat, bawang bombay, paprika, dan zaitun hitam.',
                'Tuangkan saus ke atas salad dan aduk perlahan hingga semua bahan terlapisi.',
                'Terakhir, masukkan keju feta yang sudah diremukkan. Aduk sekali lagi secara perlahan agar keju tidak hancur.',
                'Sajikan segera atau dinginkan di kulkas sebelum disajikan.',
            ],
        ],
        [
            'name' => 'Lontong Balap',
            'image' => 'lontong_balap.jpg',
            'country_name' => 'Indonesia',
            'cooking_time_minutes' => 45,
            'ingredients' => [
                ['name' => 'Lontong', 'amount' => 4, 'unit' => 'buah', 'notes' => 'Potong-potong'],
                ['name' => 'Tauge', 'amount' => 150, 'unit' => 'gr', 'notes' => 'Seduh air panas sebentar'],
                ['name' => 'Tahu', 'amount' => 1, 'unit' => 'buah', 'notes' => 'Goreng setengah matang, potong dadu'],
                ['name' => 'Lentho Singkong', 'amount' => 2, 'unit' => 'buah', 'notes' => 'Goreng, potong-potong'],
                ['name' => 'Bawang Goreng', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk taburan'],
                ['name' => 'Kecap Manis', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk penyajian'],
                ['name' => 'Bawang Putih', 'amount' => 5, 'unit' => 'siung', 'notes' => 'Haluskan, untuk kuah'],
                ['name' => 'Daun Bawang', 'amount' => 2, 'unit' => 'batang', 'notes' => 'Iris halus, untuk kuah'],
                ['name' => 'Merica Bubuk', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk kuah'],
                ['name' => 'Garam', 'amount' => 1, 'unit' => 'sdt', 'notes' => 'Untuk kuah'],
                ['name' => 'Gula Pasir', 'amount' => 0.5, 'unit' => 'sdt', 'notes' => 'Untuk kuah'],
                ['name' => 'Air', 'amount' => 1000, 'unit' => 'ml', 'notes' => 'Untuk kuah'],
                ['name' => 'Minyak Goreng', 'amount' => 2, 'unit' => 'sdm', 'notes' => 'Untuk menumis bumbu kuah'],
                ['name' => 'Sasa Kaldu Sapi', 'amount' => 1, 'unit' => 'sdm', 'notes' => 'Untuk kuah'],
                // 'Sate Kerang' dan 'Sambal Petis' dihapus dari 'ingredients'
            ],
            'steps' => [
                'Siapkan kuah: Panaskan minyak, tumis bawang putih halus dan irisan daun bawang hingga harum.',
                'Tuang 1000ml air ke dalam tumisan, masak hingga mendidih.',
                'Bumbui kuah dengan Sasa Kalsu Sapi, merica bubuk, garam, dan gula pasir. Aduk rata.',
                'Masak kuah hingga bumbu meresap dan matang. Koreksi rasa, angkat.',
                'Siapkan mangkuk saji.',
                'Tata potongan lontong, tahu goreng, dan lentho di dalam mangkuk.',
                'Siram dengan tauge yang sudah diseduh air panas.',
                'Tuangkan kuah kaldu sapi panas ke atasnya.',
                'Beri taburan bawang goreng dan kecap manis.',
                'Sajikan Lontong Balap selagi hangat bersama sate kerang dan sambal petis.', // Tetap disebut di langkah
            ],
        ],

            ];

            foreach ($recipes as $data) {
                $filePath = database_path('seeders/images/' . $data['image']);

                if (!file_exists($filePath)) {
                    $this->command->error("❌ File gambar tidak ditemukan: {$data['image']}");
                    continue;
                }

                // Upload ke MinIO
                $path = Storage::disk('s3')->putFile('recipe-images', new File($filePath), 'public');
                if (!$path) {
                    $this->command->error("⚠️ Gagal upload gambar {$data['name']} ke MinIO.");
                    continue;
                }

                $imageUrl = Storage::disk('s3')->url($path);

                // Buat atau ambil country
                $country = Country::firstOrCreate(['name_country' => $data['country_name']]);

                // Buat resep
                $recipe = Recipe::create([
                    'name_recipe' => $data['name'],
                    'image_url' => $imageUrl,
                    'cooking_time_minutes' => $data['cooking_time_minutes'],
                    'category_id' => null,
                    'country_id' => $country->id,
                ]);

                $this->command->info("✅ Resep \"{$data['name']}\" berhasil dibuat (Negara: {$data['country_name']}).");

                // Tambah bahan
                foreach ($data['ingredients'] as $item) {
                    $ingredient = Ingredients::firstOrCreate(['name_ingredients' => $item['name']]);
                    $unit = Unit::where('abbreviation', $item['unit'])->first();

                    $recipe->ingredients()->attach([
                        $ingredient->id => [
                            'amount' => $item['amount'],
                            'unit_id' => $unit?->id,
                            'notes' => $item['notes'],
                        ],
                    ]);
                }

                // Tambah langkah
                $steps = [];
                foreach ($data['steps'] as $i => $step) {
                    $steps[] = ['step_number' => $i + 1, 'instruction' => $step];
                }
                $recipe->steps()->createMany($steps);

                $this->command->info("🧂 Bahan & langkah untuk {$data['name']} berhasil ditambahkan.\n");
            }
        });
    }
}
